/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ProjectConfigurationSchema {
  /**
   * The name of the project.
   */
  name: string;
  /**
   * Array of hidden layers in the project.
   */
  hidden_layers: {
    /**
     * An array representing the size of each layer.
     */
    size: number[];
    /**
     * The type of the hidden layer.
     */
    type: "Dense" | "Convolution" | "Max pooling";
    /**
     * Optional configuration for the hidden layer.
     */
    config?: {
      /**
       * Number of filters (for layers like Convolution).
       */
      filters?: number;
      /**
       * The activation function for the layer.
       */
      activation?: "sig" | "ReLU" | "linear" | "Softmax";
    };
  }[];
  /**
   * Input configuration of the project.
   */
  input?: {
    /**
     * The type of input.
     */
    type:
      | "Color Image"
      | "Black and White Image"
      | "Audio"
      | "Text"
      | "Identification"
      | "Function of the output"
      | "Other";
    /**
     * Optional size for the input.
     */
    size?: number;
  };
  /**
   * Output configuration of the project.
   */
  output?: {
    /**
     * The type of output.
     */
    type: "Color Image" | "Black and White Image" | "Audio" | "Token" | "Identification" | "Other";
    /**
     * Optional size for the output.
     */
    size?: number;
  };
  /**
   * Optional path to the training data.
   */
  training_data_path?: string;
  /**
   * The number of training epochs.
   */
  epochs: number;
}
